name: iOS CI/CD (Xcode 26)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-14

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.app

      - name: Xcode version
        run: xcodebuild -version

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Install Transporter
        run: brew install --cask transporter

      - name: Verify Transporter
        run: |
          ls /Applications/Transporter.app/Contents/itms/bin/
          /Applications/Transporter.app/Contents/itms/bin/iTMSTransporter -version

      - name: Set Transporter path
        run: echo "FASTLANE_ITUNES_TRANSPORTER_PATH=/Applications/Transporter.app/Contents/itms/bin/iTMSTransporter" >> $GITHUB_ENV

      - name: Debug transporter path
        run: echo $FASTLANE_ITUNES_TRANSPORTER_PATH

      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build & Upload to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_KEY }}
        run: fastlane beta --verbose
